version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    container_name: base

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
